// AUTO-GENERATED by scripts/gen-islands.ts
// Do not edit manually.

import { IslandMarker } from './islands'

export function CopyButtonIsland(p: { props?: any; fallback?: any }) {
  return <IslandMarker name="CopyButton" props={p.props ?? {}} fallback={p.fallback} />
}
