import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { join, relative, sep, posix } from 'node:path'

type PageEntry = {
  file: string
  routePath: string
  importPath: string
}

const ROOT = process.cwd()
const PAGES_DIR = join(ROOT, 'src', 'pages')
const OUT_FILE = join(ROOT, 'src', 'routes.fs.gen.ts')

function toPosix(p: string) {
  return p.split(sep).join(posix.sep)
}

function walk(dir: string, out: string[]) {
  if (!existsSync(dir)) return
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const st = statSync(full)
    if (st.isDirectory()) {
      if (name.startsWith('_')) continue
      walk(full, out)
      continue
    }

    if (!st.isFile()) continue
    if (name === 'page.tsx') out.push(full)
  }
}

function segmentToPath(seg: string) {
  // [id] -> :id
  const m1 = seg.match(/^\[(.+)\]$/)
  if (m1) {
    const inner = m1[1]
    const mCatch = inner.match(/^\.{3}(.+)$/)
    if (mCatch) return '*'
    return `:${inner}`
  }

  return seg
}

function fileToRoutePath(file: string) {
  // file: .../src/pages/foo/[id]/page.tsx
  const rel = relative(PAGES_DIR, file)
  const parts = toPosix(rel).split('/')
  // drop trailing page.tsx
  parts.pop()

  const segs = parts.filter(Boolean).map(segmentToPath)
  const path = '/' + segs.join('/')
  return path === '/' ? '/' : path
}

function fileToImportPath(file: string) {
  // routes.fs.gen.ts lives under src/, so import path is relative to src
  const relFromSrc = relative(join(ROOT, 'src'), file)
  return './' + toPosix(relFromSrc).replace(/\.tsx$/, '')
}

const files: string[] = []
walk(PAGES_DIR, files)

const pages: PageEntry[] = files
  .map((file) => ({
    file,
    routePath: fileToRoutePath(file),
    importPath: fileToImportPath(file),
  }))
  .sort((a, b) => a.routePath.localeCompare(b.routePath))

const lines: string[] = []
lines.push(`// AUTO-GENERATED by scripts/gen-routes.ts`)
lines.push(`// Do not edit manually.`)
lines.push('')
lines.push(`import type { RouteDef } from './route'`)

const entries: string[] = []
pages.forEach((p, i) => {
  const alias = `p${i}`

  lines.push(`import * as ${alias} from ${JSON.stringify(p.importPath)}`)

  const m = `(${alias} as any)`
  // Require a component export (default or named)
  const componentExpr = `(${m}.default ?? ${m}.component)`

  entries.push(
    [
      '  {',
      `    path: ${JSON.stringify(p.routePath)},`,
      `    client: (${m}.client ?? false) as boolean,`,
      `    loader: ${m}.loader,`,
      `    action: ${m}.action,`,
      `    component: ${componentExpr} as any,`,
      '  }',
    ].join('\n'),
  )
})

lines.push('')
lines.push(`export const fsRoutes: RouteDef[] = [`)
lines.push(entries.join(',\n'))
lines.push(`]`)
lines.push('')

writeFileSync(OUT_FILE, lines.join('\n'), 'utf8')
console.log(`[gen-routes] wrote ${OUT_FILE} (${pages.length} route(s))`)
