import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { join, relative, sep, posix } from 'node:path'

type Entry = { file: string; importPath: string; stem: string }

const ROOT = process.cwd()
const ISLANDS_DIR = join(ROOT, 'src', 'islands')
const OUT_CLIENT = join(ROOT, 'src', 'client', 'islands.gen.ts')
const OUT_SERVER = join(ROOT, 'src', 'server', 'islands.gen.tsx')

function toPosix(p: string) {
  return p.split(sep).join(posix.sep)
}

function walk(dir: string, out: Entry[]) {
  if (!existsSync(dir)) return
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const st = statSync(full)
    if (st.isDirectory()) {
      walk(full, out)
      continue
    }
    if (st.isFile() && name.endsWith('.client.tsx')) {
      // islands.gen.ts lives under src/client
      const rel = relative(join(ROOT, 'src', 'client'), full)
      const importPath = './' + toPosix(rel).replace(/\.tsx$/, '')
      const stem = name.replace(/\.client\.tsx$/, '')
      out.push({ file: full, importPath, stem })
    }
  }
}

const entries: Entry[] = []
walk(ISLANDS_DIR, entries)
entries.sort((a, b) => a.importPath.localeCompare(b.importPath))

const imports: string[] = []
const regs: string[] = []

const serverHelpers: string[] = []

entries.forEach((e, i) => {
  const alias = `m${i}`
  const stem = JSON.stringify(e.stem)
  imports.push(`import * as ${alias} from ${JSON.stringify(e.importPath)}`)

  // Keep it bundler-friendly: docs site islands must have a default export.
  const nameExpr = `${alias}.ISLAND_NAME ?? ${stem}`
  const compExpr = `${alias}.default`

  regs.push(`  [${nameExpr}]: ${compExpr}`)

  // Server helpers use a stable string id (file stem). Keep it simple.
  serverHelpers.push(
    `export function ${e.stem}Island(p: { props?: any; fallback?: any }) {\n` +
      `  return <IslandMarker name=${stem} props={p.props ?? {}} fallback={p.fallback} />\n` +
      `}`,
  )
})

const fileClient = `// AUTO-GENERATED by scripts/gen-islands.ts\n// Do not edit manually.\n\nimport type { IslandRegistry } from './islands'\n\n${imports.join('\n')}\n\nexport const islands: IslandRegistry = {\n${regs.join(',\n')}\n}\n`

const fileServer = `// AUTO-GENERATED by scripts/gen-islands.ts\n// Do not edit manually.\n\nimport { IslandMarker } from './islands'\n\n${serverHelpers.join('\n\n')}\n`

writeFileSync(OUT_CLIENT, fileClient, 'utf8')
writeFileSync(OUT_SERVER, fileServer, 'utf8')
console.log(`[gen-islands] wrote ${OUT_CLIENT} (${entries.length} island(s))`)
console.log(`[gen-islands] wrote ${OUT_SERVER} (${entries.length} island(s))`)
