// AUTO-GENERATED by scripts/gen-routes.ts
// Do not edit manually.

import type { RouteDef } from './route'
import * as p0 from "./pages/page"
import * as p1 from "./pages/reference/page"
import * as p2 from "./pages/reference/actions/page"
import * as p3 from "./pages/reference/csrf-flash/page"
import * as p4 from "./pages/reference/data-loading/page"
import * as p5 from "./pages/reference/faq/page"
import * as p6 from "./pages/reference/file-router/page"
import * as p7 from "./pages/reference/routing/page"
import * as p8 from "./pages/reference/security/page"
import * as p9 from "./pages/reference/use-client/page"
import * as p10 from "./pages/reference/workers-deploy/page"

export const fsRoutes: RouteDef[] = [
  {
    path: "/",
    client: ((p0 as any).client ?? false) as boolean,
    loader: (p0 as any).loader,
    action: (p0 as any).action,
    component: ((p0 as any).default ?? (p0 as any).component) as any,
  },
  {
    path: "/reference",
    client: ((p1 as any).client ?? false) as boolean,
    loader: (p1 as any).loader,
    action: (p1 as any).action,
    component: ((p1 as any).default ?? (p1 as any).component) as any,
  },
  {
    path: "/reference/actions",
    client: ((p2 as any).client ?? false) as boolean,
    loader: (p2 as any).loader,
    action: (p2 as any).action,
    component: ((p2 as any).default ?? (p2 as any).component) as any,
  },
  {
    path: "/reference/csrf-flash",
    client: ((p3 as any).client ?? false) as boolean,
    loader: (p3 as any).loader,
    action: (p3 as any).action,
    component: ((p3 as any).default ?? (p3 as any).component) as any,
  },
  {
    path: "/reference/data-loading",
    client: ((p4 as any).client ?? false) as boolean,
    loader: (p4 as any).loader,
    action: (p4 as any).action,
    component: ((p4 as any).default ?? (p4 as any).component) as any,
  },
  {
    path: "/reference/faq",
    client: ((p5 as any).client ?? false) as boolean,
    loader: (p5 as any).loader,
    action: (p5 as any).action,
    component: ((p5 as any).default ?? (p5 as any).component) as any,
  },
  {
    path: "/reference/file-router",
    client: ((p6 as any).client ?? false) as boolean,
    loader: (p6 as any).loader,
    action: (p6 as any).action,
    component: ((p6 as any).default ?? (p6 as any).component) as any,
  },
  {
    path: "/reference/routing",
    client: ((p7 as any).client ?? false) as boolean,
    loader: (p7 as any).loader,
    action: (p7 as any).action,
    component: ((p7 as any).default ?? (p7 as any).component) as any,
  },
  {
    path: "/reference/security",
    client: ((p8 as any).client ?? false) as boolean,
    loader: (p8 as any).loader,
    action: (p8 as any).action,
    component: ((p8 as any).default ?? (p8 as any).component) as any,
  },
  {
    path: "/reference/use-client",
    client: ((p9 as any).client ?? false) as boolean,
    loader: (p9 as any).loader,
    action: (p9 as any).action,
    component: ((p9 as any).default ?? (p9 as any).component) as any,
  },
  {
    path: "/reference/workers-deploy",
    client: ((p10 as any).client ?? false) as boolean,
    loader: (p10 as any).loader,
    action: (p10 as any).action,
    component: ((p10 as any).default ?? (p10 as any).component) as any,
  }
]
