// AUTO-GENERATED by scripts/gen-islands.ts
// Do not edit manually.

import type { IslandRegistry } from './islands'

import * as m0 from "./../islands/CopyButton.client"

export const islands: IslandRegistry = {
  [m0.ISLAND_NAME ?? "CopyButton"]: m0.default
}
